@host = https://api.rach.io/1
@rest_api = https://cloud-rest.rach.io
@api_key = bla

### get user_id
GET {{host}}/public/person/info
Authorization: Bearer {{api_key}}

### get info (device_id)
GET {{host}}/public/person/{{user_id}}
Authorization: Bearer {{api_key}}


### Get location id
GET {{rest_api}}/device/getDevice/{{device_id}}
Authorization: Bearer {{api_key}}

### Get schedules
POST {{rest_api}}/location/getCalendarForTimeRange
Authorization: Bearer {{api_key}}

{
    "location_id": "{{location_id}}",
    "start_time": "{{$datetime iso8601}}",
    "end_time": "{{$datetime iso8601 10 d}}"
}

# {
#     "location_id": "{{location_id}}",
#     "start_time":"2021-04-01T05:00:00.000Z",
#     "end_time":"2021-05-01T04:59:59.999Z"
# }
